config/routes.rb
UF::Application.routes.draw do
  
  devise_for :users
  get "assignments" => "welcome#assignments", :as => "assignments"
  resources :goods, :except => [ :destroy , :index ] do
    resources :comments, :except => [ :index , :show ]
  end
  
  scope :path => '/goods' , :controller => 'goods' do
    get '/close/:id' => :close , :as => 'close_good'
    get '/warn/:id'  => :warn  , :as => 'warn_good'
  end
  
  
  scope :path => '/market', :controller => 'market' do
    get '/(page/:page)' => :index, :constraint => { :page => /\d+/ } ,                :as => 'market'
    get '/search(/page/:page)' => :search, :constraint => { :page => /\d+/ } ,        :as => 'market_search'
    get '/category/:id(/page/:page)' => :category, :constraint => { :page => /\d+/ } , :as => 'market_category'
  end

  
  scope :path => '/', :controller => 'problemsets' do
    get '/ps1' => :ps1, :as => '/ps1'
    get '/ps3' => :ps3, :as => '/ps3'
    get '/ps4' => :ps4, :as => '/ps4'
    get '/ps5' => :ps5, :as => '/ps5'
    get '/ps6' => :ps6, :as => '/ps6'
  end

  get "problemset2/index", :as => '/ps2'
  get "problemset2/create"
  get "problemset2/search"
  post "problemset2/create"
  post "problemset2/upload"
  get "problemset2/disable"
  get "problemset2/cleanup"

  root to: 'market#index'

  

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :user
  belongs_to :good
  validates :content, :presence => true  
  
  
  def owned_by?( user )
    user.id == self.user_id if user
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  
  # def new 
  #   @comment = Comment.new
  # end
  
  def create
    @comment = Comment.new comment_params( params )
    @good    = Good.find params[ :good_id ]
    @comment.good = @good
    @comment.user_id = current_user.id
    
    respond_to do |format|
      if @comment.save
        format.html { redirect_to good_path( @good.id ) }
        format.js   { render 'create_success' }
      else
        format.html do
          flash[:error] = 'Cannot create comment'
          redirect_to good_path( @good.id )
        end
        format.js { render 'create_fail' }
      end
    end
  end
  
  def edit
    @good = Good.find params[ :good_id ]
    @comment = Comment.find params[ :id ]
  end
  
  def update
    @good = Good.find params[ :good_id ]
    @comment = Comment.find params[ :id ]
    
    respond_to do |format|
      if @comment.update_attributes( comment_params( params ) ) 
        format.html { redirect_to good_path( @good.id ) }
        format.js   { render "update_success" }
      else
        format.html do
          flash[:error] = 'Cannot update comment'
          redirect_to good_path( @good.id )
        end
        format.js { render 'update_fail' }
      end #if
    end #respond
  end #def
  
  def destroy
  end
  
  
  protected
  def comment_params( params )
    params.require( :comment ).permit( :content )
  end
  
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_form.html.erb
<div class="comment-form" style="<%= 'display:none;' if hidden %>" id="comment-form-<%= id %>">
	<%= form_for( [ good , comment ] , :remote => true ) do |f| %>
		<%= f.text_area :content %>
		<div class="field-error">
			<%= comment.errors[:content].first %>
		</div>
		<div class="comment-submit">
			<%= f.submit %>
		</div>
	<% end %>
</div>

app/views/comments/_show.html.erb
<div class="comment" id="comment-show-<%= comment.id %>">
	<%= image_tag comment.user.avatar.url(:thumb) %>
	<div class="comment-text">
		<span class="comment-user"><%= comment.user.user_name %></span>
		<span class="comment-time"><%= distance_of_time_in_words_to_now comment.created_at %></span>
		<span class="comment-content"><%= comment.content %></span>

		<% if user_signed_in? and comment.owned_by?( current_user ) %>
			<%= link_to "Edit", edit_good_comment_path( comment.good_id , comment.id ), remote: true %>
		<% end %>
	</div>
	
	
</div>

app/views/comments/create_fail.js.erb
$( '#comment-form-new' ).replaceWith( "<%= j render( :partial => 'form' , :locals => { :comment => @comment , :good => @good , :hidden => false, :id => 'new'}) %>" );

app/views/comments/create_success.js.erb
$( '#comments' ).append( "<%= j render( :partial => 'show' , :locals => { :comment => @comment })%>" );

$( '#comment-form-new form')[0].reset();
$( '#comment-form-new' ).hide();
$( '#show-comment-form-link' ).show();

app/views/comments/edit.js.erb
$( '#comment-show-<%= @comment.id %>' ).replaceWith( "<%= j render( :partial => 'form' , :locals => { :comment => @comment, :good => @good, :hidden => false, :id => @comment.id })%>" );

app/views/comments/update_fail.js.erb
$( '#comment-form-<%= @comment.id %>' ).replaceWith( "<%= j render( :partial => 'form' , :locals => { :comment => @comment , :good => @good , :hidden => false, :id => @comment.id }) %>" );

app/views/comments/update_success.js.erb
$( '#comment-form-<%= @comment.id %>' ).replaceWith( "<%= j render( :partial => 'show' , :locals => { :comment => @comment })%>" );