config/routes.rb
UF::Application.routes.draw do
  
  devise_for :users
  get "assignments" => "welcome#assignments", :as => "assignments"
  resources :goods, :except => [ :destroy , :index ] do
    resources :comments, :except => [ :index , :show ]
  end
  
  scope :path => '/goods' , :controller => 'goods' do
    get '/close/:id' => :close , :as => 'close_good'
    get '/warn/:id'  => :warn  , :as => 'warn_good'
  end
  
  
  scope :path => '/market', :controller => 'market' do
    get '/(page/:page)' => :index, :constraint => { :page => /\d+/ } ,                :as => 'market'
    get '/search(/page/:page)' => :search, :constraint => { :page => /\d+/ } ,        :as => 'market_search'
    get '/category/:id(/page/:page)' => :category, :constraint => { :page => /\d+/ } , :as => 'market_category'
  end

  
  scope :path => '/', :controller => 'problemsets' do
    get '/ps1' => :ps1, :as => '/ps1'
    get '/ps3' => :ps3, :as => '/ps3'
    get '/ps4' => :ps4, :as => '/ps4'
    get '/ps5' => :ps5, :as => '/ps5'
    get '/ps6' => :ps6, :as => '/ps6'
  end

  get "problemset2/index", :as => '/ps2'
  get "problemset2/create"
  get "problemset2/search"
  post "problemset2/create"
  post "problemset2/upload"
  get "problemset2/disable"
  get "problemset2/cleanup"

  root to: 'market#index'

  

end

app/controllers/market_controller.rb
class MarketController < ApplicationController

  def index
    @goods = Good.all_open.paginate( :page => page , :per_page => per_page )
    @categories = Category.all
  end
  
  def search
    @keyword = params[:keyword]
    @results = Good.all_open
                  .includes( :user )
                  .where('title @@ :q or description @@ :q or users.email ilike :q' , :q => @keyword)
                  .paginate( :page => page , :per_page => per_page )
    #render 'index'
  end
  
  def category
    @categories = Category.all
    @category = Category.find params[:id]
    @goods = @category.goods.all_open.paginate( :page => page , :per_page => per_page )
  end

  private
  def page
    params[:page] ? params[:page] : 1
  end
  
  def per_page
    6
  end
end

app/helpers/market_helper.rb
module MarketHelper
end

app/views/market/_categories.html.erb
<ul id="category-bar">
	<% categories.each do |c| %>
		<li><%= link_to c.category_title, market_category_path( :id => c.id ) %></li>
	<% end %>
</ul>

app/views/market/_goods.html.erb
<% if goods.empty? %>
<div>
	Sorry, our market doesn't have what you're looking for
</div>-
<% else %>

<div class="masonry">
	<% goods.each do |good| %>
		<%= link_to good_path( good.id ) do %>
			<div class="item">
				<%= image_tag good.image.url(:thumb), :class => 'item-image' %>
				<div class="item-detail">
					<span class="item-title"><%= good.title %></span>
					<span class="item-price"><%= good.price %></span>
					<span class="item-category"><%= good.category.category_title %></span>

					<div class="item-owner">
						<span class="item-owner-name"><%= good.user.user_name %></span>

						<%= image_tag good.user.avatar.url(:thumb) , class: 'item-owner-avatar' %>
					</div> <!-- item-owner -->
				</div> <!-- item-detail -->
			</div> <!-- item -->
		<% end %> <!-- link-to -->
	<% end %> <!-- each -->
</div> <!-- .masonry -->

<% end %>

app/views/market/category.html.erb
<%= form_tag market_search_path , :method => :get , :id => 'search-bar' do %>
	<%= label_tag "Keyword:" %>
	<%= text_field_tag :keyword %>
	<%= submit_tag 'Search'%>
<% end %>

<div class="market-actions-bar">
	<%= link_to "Post new product", new_good_path, :class => 'new-good-link' %>
</div>

<h1>Category - <%= @category.category_title %></h1>

<%= render :partial => 'goods' , :locals => { :goods => @goods } %>
<%= render :partial => 'categories' , :locals => { :categories => @categories } %>

<%= link_to "Back to Market", market_path %>

<div class="page-foot">
	<%= will_paginate @goods %>
</div>

app/views/market/index.html.erb
<%= form_tag market_search_path , :method => :get , :id => 'search-bar' do %>
	<%= label_tag "Keyword:" %>
	<%= text_field_tag :keyword %>
	<%= submit_tag 'Search'%>
<% end %>

<div class="market-actions-bar">
	<%= link_to "Post new product", new_good_path, :class => 'new-good-link' %>
</div>


<%= render :partial => 'categories' , :locals => { :categories => @categories } %>

<%= render :partial => 'goods' , :locals => { :goods => @goods } %>
<div class="page-foot">
	<%= will_paginate @goods %>
</div>

app/views/market/search.html.erb
<%= form_tag market_search_path , :method => :get , :id => 'search-bar' do %>
	<%= label_tag "Keyword:" %>
	<%= text_field_tag :keyword %>
	<%= submit_tag 'Search'%>
<% end %>

<h1>Search</h1>

<h2>You're seraching "<%= @keyword %>"</h2>

<%= render :partial => 'goods' , :locals => { :goods => @results } %>

<%= link_to "Back to Market", market_path %>

<div class="page-foot">
	<%= will_paginate @results %>
</div>