config/routes.rb
UF::Application.routes.draw do
  
  devise_for :users
  get "assignments" => "welcome#assignments", :as => "assignments"
  resources :goods, :except => [ :destroy , :index ] do
    resources :comments, :except => [ :index , :show ]
  end
  
  scope :path => '/goods' , :controller => 'goods' do
    get '/close/:id' => :close , :as => 'close_good'
    get '/warn/:id'  => :warn  , :as => 'warn_good'
  end
  
  
  scope :path => '/market', :controller => 'market' do
    get '/(page/:page)' => :index, :constraint => { :page => /\d+/ } ,                :as => 'market'
    get '/search(/page/:page)' => :search, :constraint => { :page => /\d+/ } ,        :as => 'market_search'
    get '/category/:id(/page/:page)' => :category, :constraint => { :page => /\d+/ } , :as => 'market_category'
  end

  
  scope :path => '/', :controller => 'problemsets' do
    get '/ps1' => :ps1, :as => '/ps1'
    get '/ps3' => :ps3, :as => '/ps3'
    get '/ps4' => :ps4, :as => '/ps4'
    get '/ps5' => :ps5, :as => '/ps5'
    get '/ps6' => :ps6, :as => '/ps6'
  end

  get "problemset2/index", :as => '/ps2'
  get "problemset2/create"
  get "problemset2/search"
  post "problemset2/create"
  post "problemset2/upload"
  get "problemset2/disable"
  get "problemset2/cleanup"

  root to: 'market#index'

  

end

app/controllers/problemsets_controller.rb
class ProblemsetsController < ApplicationController

	def ps1

		begin
	      @thisIsCausingZeroErro = 0/0
	      rescue ZeroDivisionError => ex
	        logger.error (Time.now.to_s + 'User triggered zero division error')
	        @error = "User Just Triggered error of division by 0"
	    end

	    agent = Mechanize.new
	    #agent.set_proxy '192.41.170.23', 3128
	    agent.get('http://www.yahoo.com')
	    @listFromYahoo = agent.page.search('ol[@class="lh-192 trendingnow_trend-list fw-b"]/li/a') 
	end

	def ps2
	end

	def ps3
	end

	def ps4
	end

	def ps5
	end

	def ps6
	end
end

app/helpers/problemsets_helper.rb
module ProblemsetsHelper
end

app/views/problemsets/_psfooter.html.erb
<%= link_to "Back to Assignments", assignments_path %>

app/views/problemsets/ps1.html.erb
<h1> Problemset One </h1>
<hr >

<h2>Problem Set 1: Question 1</h2>
<p>
	Figure out how to add a XHTML syntax validation link to the site view layout at the bottom of your pages, and do it.
</p>


For this question, we added 'render "layouts/footer"' to our application.html.erb under layouts folder. 
<br />
Asking rails to render uniform footer fatched from layouts/_footer.html.erb.  


<h2>Problem Set 1: Question 2</h2>
<p>In your controller for this problem set, add code that generates a divide-by-zero exception. Figure out how to get your server (in production mode) to output a stack trace to the browser when such an exception occurs. (Later, however, you’ll want to turn this off as it is not considered a best security practice.) Find the error log for your production server. Add code to your controller that logs a message “About to divide by 0” to that error log just before you divide by 0. In your index to your solution to this problem set, explain how this is done (in English).
</p>

<%= @error %>

<h2>Problem Set 1: Question3</h2>
<p>Create a Web page that, when accessed, fetches the 10 links currently in the “Trending Now” box at yahoo.com. Your code should figure out how to access the link data and slurp them into your own page. Note that you should do all the processing on the server and output a static HTML page (do not do any fancy Javascript here).</p>

<% @listFromYahoo.each do |item| %>
  <li><%= link_to item.text, item['href'], target: '_blank' %></li>
<%end%>

<%= render :partial => 'psfooter' %>

app/views/problemsets/ps3.html.erb
<h1> Problemset Three </h1>

<h2><%= link_to "Our Plans", "/pdf/assignment_3.pdf" %></h2>

<%= render :partial => 'psfooter' %>

app/views/problemsets/ps4.html.erb
<h1> Problemset Four </h1>

<h2><%= link_to "Our Plans", "/pdf/assignment_4.pdf" %></h2>

<%= render :partial => 'psfooter' %>

app/views/problemsets/ps5.html.erb
<h1> Problemset Five </h1>

<h2><%= link_to "Our Plans", "/pdf/assignment_5.pdf" %></h2>

<%= render :partial => 'psfooter' %>

app/views/problemsets/ps6.html.erb
<h1> Problemset Six </h1>

<h2><%= link_to "Our Evals", "/pdf/assignment_6.pdf" %></h2>

<%= render :partial => 'psfooter' %>