config/routes.rb
UF::Application.routes.draw do
  
  devise_for :users
  get "assignments" => "welcome#assignments", :as => "assignments"
  resources :goods, :except => [ :destroy , :index ] do
    resources :comments, :except => [ :index , :show ]
  end
  
  scope :path => '/goods' , :controller => 'goods' do
    get '/close/:id' => :close , :as => 'close_good'
    get '/warn/:id'  => :warn  , :as => 'warn_good'
  end
  
  
  scope :path => '/market', :controller => 'market' do
    get '/(page/:page)' => :index, :constraint => { :page => /\d+/ } ,                :as => 'market'
    get '/search(/page/:page)' => :search, :constraint => { :page => /\d+/ } ,        :as => 'market_search'
    get '/category/:id(/page/:page)' => :category, :constraint => { :page => /\d+/ } , :as => 'market_category'
  end

  
  scope :path => '/', :controller => 'problemsets' do
    get '/ps1' => :ps1, :as => '/ps1'
    get '/ps3' => :ps3, :as => '/ps3'
    get '/ps4' => :ps4, :as => '/ps4'
    get '/ps5' => :ps5, :as => '/ps5'
    get '/ps6' => :ps6, :as => '/ps6'
  end

  get "problemset2/index", :as => '/ps2'
  get "problemset2/create"
  get "problemset2/search"
  post "problemset2/create"
  post "problemset2/upload"
  get "problemset2/disable"
  get "problemset2/cleanup"

  root to: 'market#index'

  

end

app/models/good.rb
class Good < ActiveRecord::Base
  validates :title, :presence => true
  validates :price, :numericality => { greater_than: 0 }
  
  belongs_to :user
  belongs_to :category
  before_create :assign_default_status
  has_attached_file :image, :styles => { :medium => "500x500>", :thumb => "250x250>"},  :default_url => "/images/missing.jpeg"

  has_many :comments
  
  %w(open close warned).each do |method|
    define_method( "#{method}!" ) { self.status = method }
    define_method( "#{method}?" ) { self.status == method }
    scope "all_#{method}", -> { where :status => method }
  end
  
  def owned_by?( user )
    self.user_id == user.id if user
  end
  
  protected
  def assign_default_status
    self.status ||= 'open'
  end
  
end

app/controllers/goods_controller.rb
class GoodsController < ApplicationController
  before_action :require_logged_in, :only => [ :new , :create , :edit , :update , :close , :warn ]
  before_action :recheck_owner, :only => [ :edit , :update , :close ]
  
  def new 
    @good = Good.new
  end
  
  def create
    @good = Good.new good_params( params )
    @good.user = current_user if current_user
    
    if @good.save
      flash[:message] = "#{@good.title} is created"
      redirect_to good_path( @good.id )
    else
      render 'new'
    end
  end
  
  def edit
    #@good = Good.find params[:id]
  end
  
  def update
    #@good = Good.find params[:id]
    if @good.update_attributes good_params( params )
      flash[:message] = "#{@good.title} is updated"
      redirect_to good_path( @good.id )
    else
      render 'edit'
    end
  end 
  
  def show
    @good = Good.find params[:id]
  end
  
  def close
    #@good = Good.find params[:id]
    @good.close!
    @good.save
    
    redirect_to good_path( @good.id )
  end
  
  def warn
    @good = Good.find params[:id]
    @good.warned!
    @good.save
    
    redirect_to good_path( @good.id )
  end
  
  private
  def good_params( params )
    params.required( :good ).permit( :title , :price , :category_id  ,:description, :image)
  end
  
  def require_logged_in
    unless user_signed_in?
      flash[:error] = 'Please Log In before posting goods'
      redirect_to new_user_session_path 
    end
  end
  
  def recheck_owner
     @good = Good.find params[:id]
    unless @good.owned_by?( current_user )
      flash[:error] = 'You dont own this item!'
      redirect_to good_path( @good.id )
    end
  end

end

app/helpers/goods_helper.rb
module GoodsHelper
end

app/views/goods/_form.html.erb
<%= form_for(@good) do |f| %>
	<%= error_header @good %>

  <div class="field">
    <%= f.label      :title %>
    <%= f.text_field :title %>
  </div>
  
  <div class="field">
      <%= f.label        :price %>
      <%= f.number_field :price %>
  </div>
  
  <div class="field">
      <%= f.label     :description %>
      <%= f.text_area :description %>
  </div>
  
  <div class="field">
      <%= f.label     :category %>
      <%= f.select :category_id , Category.all.collect{ |c| [c.category_title, c.id] }%>
  </div>

  <div class="field">
      <%= f.label     :image %>
      <%= f.file_field :image %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/goods/edit.html.erb
<h1>Edit Good</h1>

<%= render :partial => 'form' %>

app/views/goods/new.html.erb
<h1>New Good</h1>

<%= render :partial => 'form' %>

app/views/goods/show.html.erb
<h1><%= @good.title %></h1>

<% if @good.close? %>
	<span class="warning-msg">This good is closed</span>
<% end %>

<% if @good.warned? %>
	<span class="warning-msg">This good is warned</span>
<% end %>

<% if flash[:messge] %>
	<span class="message"><%= flash[:messge] %></span>
<% end %>

<%= image_tag @good.image.url, :class => 'good-image' %>
<div id="good-detail">

	<div>
		<label>Price</label>
		<span class="value"><%= @good.price %></span>
	</div>

	<div>
		<label>Owner</label>
		<span class="value"><%= @good.user.email unless @good.user.nil? %></span>
	</div>

	

	<div>
		<label>Category</label>
		<span class="value"><%= @good.category.category_title %></span>
	</div>

	<%=raw sanitize(simple_format(@good.description), :tags => %w(br p)) %>
	<div class="panel">
		<%= link_to 'Edit' ,  edit_good_path( @good.id ) if @good.owned_by? current_user %> 
		<%= link_to 'Report Inappropriate' ,  warn_good_path( @good.id ) if user_signed_in? and !@good.owned_by?( current_user ) %>  
		<%= link_to 'Close' , close_good_path( @good.id ) if @good.owned_by? current_user %> 
	</div>
</div>

<hr />
<%= link_to 'Back to Market' , market_path %>

<h2>Comments</h2>
<div id="comments">
	<% @good.comments.each do |comment| %>
		<%= render :partial => 'comments/show' , :locals => { :comment => comment } %>
	<% end %>
</div>

<% if user_signed_in? %>
	<%= link_to_function 'Add comment' , 'showCommentForm()' , :id => 'show-comment-form-link' %>
	<%= render :partial => 'comments/form' , :locals => { :good => @good , :comment => Comment.new , :hidden => true , :id => 'new'} %>
<% end %>